### ISSUE TITLE
hard-coded english lang strings

### ISSUE THREAD

**Issue by danmarsden** [developerck/moodle-block_analyticswidget#5]
https://github.com/developerck/moodle-block_analyticswidget/blob/main/classes/widgets/my/course_stats.php#L67

https://github.com/developerck/moodle-block_analyticswidget/blob/main/classes/widgets/my/course_stats.php#L87

All user facing strings must be in the lang pack file - this is a blocker for approval.

**Comment by developerck** [comment]
This has been corrected.
