### ISSUE TITLE
I do not display the completion status of courses in the block

### ISSUE THREAD

**Issue by VickyFloresL** [developerck/moodle-block_analyticswidget#9]
Dear @Chandra Kishor,

I expose my case:
I have configured the completion of the courses, considering some activities as a requirement, of which it shows a status of completed and others in progress in the internal block "Course completion status". However, when entering as a student and validating in the "Analytic Widgets" block, the actual status of the courses does not appear, so I would like you to help me with an installation guide or tell me what processes I must follow so that the statuses of the courses can be viewed.

Attached screenshots of the teacher and student profiles. Additional configurations made.

I appreciate your attention and I look forward to hearing your comments.

Cheers,
![Configuración de bloque AW](https://user-images.githubusercontent.com/111386419/184963436-2f660d22-9fbb-46cd-b70e-356637e12c68.JPG)
![bloque de profesor](https://user-images.githubusercontent.com/111386419/184963442-0b7df55d-27de-45c1-ad0b-9668d2101e79.JPG)
![bloque de estudiante](https://user-images.githubusercontent.com/111386419/184963446-d7de380f-57e7-4358-85c4-1567e6c3d36b.JPG)
![configuración de curso](https://user-images.githubusercontent.com/111386419/184963451-9066da91-8600-4c5f-a4ab-89e7ae37e6b9.JPG)
<img width="677" alt="estado de curso interno" src="https://user-images.githubusercontent.com/111386419/184963455-e37fac5a-ab68-4e9a-95c4-ab9e802ba3dc.png">

**Comment by developerck** [comment]
@VickyFloresL ,

Course completion cahrt is on basis of a course compeltion status.
One can setup this , under particular course > settings > course compeltion critera.
once you setup this, you will get a course completion report under  particualr course > reports > course completion report
Note : activites can be marked completed and on basis of that , course progress can be shown to 100% but still it does not make the course as completed untill course completion criteria is not setup.

if you have followed above, then i will suggest to share the detail directly to me to check the issue,
otherwise, you can try above.

waiting to hear from you.

**Comment by VickyFloresL** [comment]
Dear @developerck 
I have configured the course considering the criteria and completion dates of the course, but the actual status is still not displayed in the analytic widgets block. I send captures of the configurations and I would like you to please help me review and indicate what could be missing so that the status of completion and in progress of the user's courses is displayed.

waiting to hear from you.

![Configuración de curso](https://user-images.githubusercontent.com/111386419/185438901-67045522-ca4c-4ba5-b41c-3fd355bf4cd9.png)
<img width="710" alt="criterios de finalización" src="https://user-images.githubusercontent.com/111386419/185438911-39062af8-6957-4c48-829a-a3399386ccd7.png">
![finalización de curso-criterios](https://user-images.githubusercontent.com/111386419/185439886-9bea93d5-a7bf-487e-912d-45465217f6ad.JPG)

**Comment by developerck** [comment]
is the user currently enrolled in the course ? my means, is the enrolment active for the completed course ?

**Comment by VickyFloresL** [comment]
Dear @developerck
The registration of the users is active, would it be necessary to make any adjustments?

waiting to hear from you.

![image](https://user-images.githubusercontent.com/111386419/185659775-a7b439cd-e713-4062-b412-5a293d5729bb.png)

**Comment by developerck** [comment]
i will suggest to share the credential as teacher and url,  so that i can check more.

you can use following, https://developerck.com/connect/ to share the detail  privately.

**Comment by VickyFloresL** [comment]
Dear @developerck
Send a message through the link provided, it does not allow you to attach images so I send them here.

waiting to hear from you

![bloque de estudiante](https://user-images.githubusercontent.com/111386419/185967492-0038c77d-6abd-4c45-986d-9d0c78013929.JPG)
![bloque de profesor](https://user-images.githubusercontent.com/111386419/185967497-db66c709-5fad-4168-beeb-1b1c0014afad.JPG)
![Configuración de bloque AW](https://user-images.githubusercontent.com/111386419/185967503-5f416ff7-f787-4914-a585-661504ffaa84.JPG)
![Configuración de curso](https://user-images.githubusercontent.com/111386419/185967511-50658277-ee31-408e-a110-0fa8dead4ceb.png)
<img width="710" alt="criterios de finalización" src="https://user-images.githubusercontent.com/111386419/185967518-fdf31719-bd07-4bce-ab43-00d555bf64fa.png">
<img width="677" alt="estado de curso interno" src="https://user-images.githubusercontent.com/111386419/185967521-efc0cde6-dfd7-49c5-b53d-5f5ff97f2902.png">
.

**Comment by developerck** [comment]
I could not get that and waited for the access. as access is not granted, sol marking this close.
